### ISSUE TITLE
Setup CI for building releases

### ISSUE THREAD

**Issue by jonasKjellerup** [f-klubben/fappen#38]
Whenever a push to the release branch occurs we want a GitHub action to run with the following results:

- [ ] The project should be built and zipped, such that it is ready for deployment.
- [ ] The songbook should additionally be zipped on its own.
- [ ] A tag should be created with the aforementioned uploaded.

Additionally a GitHub action should check for the following, when merge requests into release are created:

- That the version tag has been updated.
- A changelog for said version exists.
